### ISSUE TITLE
Error: net::ERR_CONNECTION_TIMED_OUT at https://web.whatsapp.com/     at navigate (/wechaty/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/FrameManager.ts:191:13)     at processTicksAndRejections (node:internal/process/task_queues:96:5)     at async FrameManager.navigateFrame (/wechaty/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/FrameManager.ts:161:17)     at async Frame.goto (/wechaty/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/FrameManager.ts:643:12)     at async Page.goto (/wechaty/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/Page.ts:1734:12)     at async Client.initialize (/wechaty/node_modules/whatsapp-web.js/src/Client.js:99:9) 13:52:50 ERR PuppetWhatsApp start() whatsapp.initialize() rejection: Error: net::ERR_CONNECTION_TIMED_OUT at https://web.whatsapp.com/

### ISSUE THREAD

**Issue by kongdekede** [Chatie/docker-wechaty-getting-started#8]
![image](https://user-images.githubusercontent.com/44976140/157251534-885db69f-ee4f-4917-94ab-eedc1b3da967.png)

**Comment by huan** [comment]
The error log said very clearly: your network can not connect to whatsapp.

Changing your server to a VPS in the US/HK will fix this problem.
